scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: [
        '127.0.0.1:9200',
      ]
        labels:
          service: 'face-recognition-network'
          group: 'testing'
          name: 'main-server'
